### ISSUE TITLE
Broken auto-rotate

### ISSUE THREAD

**Issue by ichibauer** [ichibauer/android-kernel_m21_optio#1]
And cannot take horizontal pictures, apparently; seems like OSRC fault. 

[Dmesg, last_kmsg, & logcat](https://github.com/ichibauer/android-kernel_m215f_optio-esst/files/7186457/full-log.zip)

**Comment by ichibauer** [comment]
[Fixed](https://github.com/ichibauer/android-kernel_m215f_optio/commit/6675340067784b0b191ce8f0017b1625953e1ffe)

**Comment by Dark-Matter7232** [comment]
I will create another pr to fix it properly this time, can you mark it as `hacktoberfest-accepted`?
